{
 "title": "E-commerce - Overview",
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "30s",
 "panels": [
  {
   "title": "Débit requêtes par service (req/s)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "sum by (application) (rate(http_server_requests_seconds_count[5m]))",
     "legendFormat": "{{application}}"
    }
   ]
  },
  {
   "title": "Erreurs 5xx par service (req/s)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "sum by (application) (rate(http_server_requests_seconds_count{status=~\"5..\"}[5m]))",
     "legendFormat": "{{application}}"
    }
   ]
  },
  {
   "title": "Commandes créées (24h)",
   "type": "stat",
   "gridPos": { "h": 5, "w": 8, "x": 0, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(increase(orders_total[24h]))"
    }
   ]
  },
  {
   "title": "Users créés (24h)",
   "type": "stat",
   "gridPos": { "h": 5, "w": 8, "x": 8, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(increase(http_server_requests_seconds_count{application=\"ms-membership\",method=\"POST\",uri=\"/api/v1/users\"}[24h]))"
    }
   ]
  },
  {
   "title": "Produits créés (24h)",
   "type": "stat",
   "gridPos": { "h": 5, "w": 8, "x": 16, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(increase(http_server_requests_seconds_count{application=\"ms-product\",method=\"POST\",uri=\"/api/v1/products\"}[24h]))"
    }
   ]
  }
 ]
}